hash-format = "sha256"

[[files]]
file = "mods/.skin-layers-3d.pw.toml.kate-swp"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "e46d8030ab2b5ede482e64dc11ace6adeb90fa32397962599ea039c862cde631"
metafile = true

[[files]]
file = "mods/AdvancedPeripherals-1.20.1-0.7.46r.jar"
hash = "e78152a8acc771121772750360e6a89f14414375a5ca7df7da168b1c1f40064b"

[[files]]
file = "mods/CarryOnVSCompat-Forge-1.20.1-1.0.0.jar"
hash = "de1bba80a237490d8a9347281404c2d2cf9a35dc2ad5f0a79570fa76643a290f"

[[files]]
file = "mods/Clumps-forge-1.20.1-12.0.0.4.jar"
hash = "8af01712c0dc32cebaff31795ca6d223fddff2ea9b1f5efbd9c3a586a0dacbc0"

[[files]]
file = "mods/aetherial-islands-2.0.2.jar"
hash = "6c1bc752b632f233b28cfd5137da2e6fb1d56fb308c8f760bc321b37038bc26f"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "390d333a8870ced85f3fa4883ea9da62c11ece797b4e114b0ff40192828ab156"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a7fa7c681c6bbc5d614b527c7f234153af5a54686013282ae918f8c1e41dfc23"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "8b7928e81a965daa93af1878fb6a6bbe7756c8feecc465ba3e41013c3683d7b0"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "c01ea7652431fe3aaa1a37e907313be85e7486d0e881eaa0a46413464e30dc0c"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "e61c7eeb18b913a985d1213609c7b7b1741a7db99a437178088064db5054f5b7"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "81dd4cb04a54879fed119222ee709b632cb79a1a396b64862c0b8aded27dc841"
metafile = true

[[files]]
file = "mods/catalogue.pw.toml"
hash = "cdffd5a4b708b59529c32016944714da992733ec431c13844b41229a0f20d1bb"
metafile = true

[[files]]
file = "mods/cc-tweaked-1.20.1-forge-1.116.2.jar"
hash = "d778067958d7999c4140a70a477fbab0faa882bb6239fc396c79276d485ce772"

[[files]]
file = "mods/cc-vs.pw.toml"
hash = "a3fab34f2cc98b01b4c53034e61b18e4ef3a15b29d13af7e559e869cf259de72"
metafile = true

[[files]]
file = "mods/cc_androids-forge-1.3.0.jar"
hash = "186999254cb5fbd18eaa8fff910d88055f0b54fbe7c99d888b23be6af5c2fdaf"

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "f1e5cd46733597edd78a91e9c29ee6ae6ee0ad63addcae24e4c4e0b9f030b53e"
metafile = true

[[files]]
file = "mods/cclink-6.0.2-beta1-1.20.1.jar"
hash = "aec3b36145a46bac7013ea39f4cd76c8187e82ccfc3a7e6671b845c4181795f4"

[[files]]
file = "mods/ccx-forge-6.1.0.jar"
hash = "2da537efb1929478dc37a78edc4ccf9c11ebf235456b10e870fbf970e79c85a8"

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "9c1de22c256f96c959793b79b03825e96ba6d3dfbf6a47b47a95de45369bb780"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "fb3b04c892cf9c4ada0053e3cedff82016cdf1d2147327675f9367c8a1be383a"
metafile = true

[[files]]
file = "mods/classic-peripherals.pw.toml"
hash = "0226a674fb36a07083a324a88a187b0db511654520162f4986ea9b3ca3efd92a"
metafile = true

[[files]]
file = "mods/clockwork-0.5.4.6.jar"
hash = "b23ba45297d142cc9a412e730e64d3e67a34fc3c6b14c728020760d5cd349c4b"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3391364edc8e38f90c692b82dfd09a26c293c24d80b08c307417ac223029352"
metafile = true

[[files]]
file = "mods/cobblefordays.pw.toml"
hash = "42d8bbdfd2a42ab930ef09e4a71452b6c4e42aff605eed55937d966c041cdec7"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "9f9ec1de314ae973f53ba5fa828da3ab43bb53171974f56043ae02fc2b2457fa"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "aeb4de0e9bd94f76ca879dc8f0edf7f6d591698847943cac8f5f9b29c3966d46"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "be775f4d913d3355eeb9f7331bafe008dc963b755af1fda786578ba436a4cb22"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "f32e856351e67a62afa2f4c3e3c3d1b01383958d58aa9bfd1ed829ae246518bc"
metafile = true

[[files]]
file = "mods/corpse-forge-1.20.1-1.0.23.jar"
hash = "9f639204588512abe767bb5c2ff97d41f50352af916de939ac8029c95d57ae7b"

[[files]]
file = "mods/corpse-x-cosmetic-armor-reworked-compat.pw.toml"
hash = "5fa5f1b3775bcacc1738979697398acf2078007584bd784bebf3edf1ebdca9aa"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "5b8f6e3d4df50288cbb9d6fc79268390264a03ffb987583bbfb6aab458d4d7f4"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "3de1cc562e400b3bd066d4266da308e47ebf1473691d3385c30f94b039b98741"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "c6ba397dbf9f556ac3d80fb193b9086ead2779e04e078fbdd5059b2108b45fbf"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "8c0890363f422cf38ba702066f2eea241da5a54b61323f7b36afa6e2247fb694"
metafile = true

[[files]]
file = "mods/create-compatible-storage.pw.toml"
hash = "8a2ca74270055f1b7ef2aa522063f68284a0fd06512b3e41ea29f5651f0e0920"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "9767ff2b3582967f68717fe53d1e294d9a76250b33724f3a9563b4188ee10565"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "10cf599888880fa248166ccab7a4e28cf33cc26633b5f0c44ec615867816c196"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "e5317f9a8e38b9079096a188344f78a8d9578a2e885b7b7f0042c96ee8d4b62f"
metafile = true

[[files]]
file = "mods/create-extra-gauges.pw.toml"
hash = "7ae35cd6c1a9317af7b43c4e25140d7583be1bf64e354a3d93c05e6b2033cd28"
metafile = true

[[files]]
file = "mods/create-factory-logistics.pw.toml"
hash = "a7f8dad3609576acbf12c0757ff5d5b0645955993be18d5f553adedf5d58333f"
metafile = true

[[files]]
file = "mods/create-industry.pw.toml"
hash = "290a94fc5faf8f6de57549f95da9cf5b9d35d7eaa6d40c3770b621f4c0a50146"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "627a48e071e7df86d3551a22367a3ce16f2a6c159d9928cae4a7ca92f884cf61"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "8821b90f15e945573031ac33a316a3616bdba5e1d94fbe3e91ef9efb6fc127ec"
metafile = true

[[files]]
file = "mods/create-propulsion.pw.toml"
hash = "863a6524d31e49dade98a5fb1deddfdf953c4d293557437d845df7ca093b30da"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
hash = "0eafdd579bdd6bcc7a7c7de96798aabbcd8dc2f76d3e0ab3a1fcd70e9d80b81f"
metafile = true

[[files]]
file = "mods/create-smart-crafter.pw.toml"
hash = "87c28c70f80a45b7c91849527bf74c1318808bfdc6ac3fbeac66b4808b8bf992"
metafile = true

[[files]]
file = "mods/create-tweaked-controllers.pw.toml"
hash = "a9f66aa3eec131727a2f109edfcce4c77c76031a1087e69961eb4e637ce8feeb"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "90b5ff9cf2419fcf72f1fb15a5e9f83c2ede53f975de175c34358913f908dddd"
metafile = true

[[files]]
file = "mods/create_connected-1.1.13-mc1.20.1-all.jar"
hash = "dadc604fdf702265fcc8be0b7f6edbe133d56b6e71af61d47da999b2a045b247"

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8d80e950a5f544761cdb6deb60ec69584c79d1065b21ede372ab463b5a6a7b5f"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "72a867977697dce084eff67f425cf91feb0928e74fe9c5b5db9769f2bc98c074"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "0c537e6292c829934957c15a2711f2257191ecdf0d4867e35e22774518602ee5"
metafile = true

[[files]]
file = "mods/digital-items-3.pw.toml"
hash = "a98d5e60fbfa0b70534fc1ac54ec073511fad4b41cb72b7259b7e3a6fc6ba2da"
metafile = true

[[files]]
file = "mods/drive-by-wire.pw.toml"
hash = "6db8f945dc44a41f5fae31042a6dadd0600d6d242ac7344e7c4d1cb32ccd8212"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
hash = "f7d60e7c093c311cc2a71d30aa2b832b737419825cb5bdac613435004d21cbf7"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "4ed47eed09d7724c00627951c0049452766c52f8b5682ff75c7aba23d30360d2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "e158888b350eae7707f12155e742e6f8d34f8c66bbbb755e94766382c1c6a99c"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "c6f20dc50c93bf17c57237b84bb2fa67a774002f2719fd4d3cf8b7835e545508"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "885b411d5b49cb42c72510a507e1ac8fbfb8d87b8b86b11e756141aabfcfb24b"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "8e48fa30f2ea5bc77d8b23d06910842f50c90d4a05a10ffc3ea817fba27dd005"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6d08cdff2c035c188480d39ad3320ad1e34a5d74cd65c53f970e81f2476c93f5"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "b2116198cb91b168710a2c6685c792527d9331bedf5069a03e4c0ae9a8679b04"
metafile = true

[[files]]
file = "mods/essential-mod.pw.toml"
hash = "53683d777351eb3cbc05c1db81f6bd02975bc485ffd41fc40cc110aa58e0a78d"
metafile = true

[[files]]
file = "mods/eureka.pw.toml"
hash = "52ccbdc46d9ba3a7ce2ef96839666a553e2198d2740817e98cac1140ef3d019a"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "ffa85ac3584726fcdb7cd44225cc7bdd6cd2e485b0c4abfb34bfcb69336fd26b"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "5b1a215df0c2880cbf058016d9fa0174a159c6d1b9f206a4ec966a82696cfd3b"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "7bbcccbdbf9449a5ebe067174ea5aba33018fce30f16617a26d22a3335cf5dbd"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "0b33f4230cef2489f56f2134bc98066eff4079ea1b27b1a2efc2cbe9024ef64f"
metafile = true

[[files]]
file = "mods/grapplevs.pw.toml"
hash = "bb64b321a0858a4e0b5ecff29dba441e5ef0c50d6eb3524890aa254f62096cb8"
metafile = true

[[files]]
file = "mods/grieflogger.pw.toml"
hash = "c2d83b17590a30e370cea44ebf9c187d51943b63ce6b861977ffbe8cc310265e"
metafile = true

[[files]]
file = "mods/hypertubes.pw.toml"
hash = "1d0a3fd62756e3440c65aa475512e3ca5c2750a641565e04f42acec23586f797"
metafile = true

[[files]]
file = "mods/inv-view-forge.pw.toml"
hash = "cf60d886e4e585a9c73ea07d93fa520817015130e5cf281379dd11fb9ee42a62"
metafile = true

[[files]]
file = "mods/jade-vs.pw.toml"
hash = "f17463089d03720d003f81a88982c3a19fcfbaccaf5d3076dd879b490d61cfbf"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "95bc534f33299aed2ba4ad23f087879fd3f2902a842520364ef90ba976128266"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "3ea2755c57c3fb921fdafb33fae5284c459f40307827a54e57fb10b3390e5d98"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "a01dfc8081b5879687774d8563cc4cca3279e34ffce6dd4f6ad825e9c1448095"
metafile = true

[[files]]
file = "mods/kubejs-cc.pw.toml"
hash = "cb5f21507790bcf73f0c01559a049d014cd2a281363fdd90a27d26a6e213d469"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
hash = "2489fb086cefaf2baaaffc20218af1d8a9987bd6cfc9b5a1838919a17fbd290e"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "61e26805b807666f611bdeb373807e61e1883b662c003317216622baa935c846"
metafile = true

[[files]]
file = "mods/lectern_hub-1.0.0-1.115.0-1.20.1.jar"
hash = "6a3dba16c593644bf2a454d193bb6d6f6bcb2e17ae5d26c12aab28509475dd3b"

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "d28b47efbc52c0fd21300aa45dadb15b92fe8c718cd606759037c625d194a3d7"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "63131bf7d7e346928090c165ced87c53381b361edecd7337c2e7a839774033ab"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "abd2f49c7e244c7caf894f941e5206cf037280843d4084f1e0013c90467837bf"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "643e2939843c03c538332beab0f57483cc76e615442ec1a236b98fda4a14289a"
metafile = true

[[files]]
file = "mods/more-peripherals.pw.toml"
hash = "9f64031a8114d1980281a2476c6db63549f409bb07d8bc0b6a01394238072d17"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "63721f91e34bd6cdbbfa0c22b6d868e4dbb3c33d683e0dabef2cd79fd2000b4c"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "b8520ec1d30946a3df1bfb38017ee652812a373f8bc9c964c8f5b28decfa99c6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "816c4af5ac97051e4fdd9101bde0568afb762d55d9370e917cfc717e463192e1"
metafile = true

[[files]]
file = "mods/no-chat-restrictions.pw.toml"
hash = "f3be8ee5e1f9bd2b641d5113125f3ceb1387aef09f898b7da19cf23cb42f261c"
metafile = true

[[files]]
file = "mods/no-more-mineshafts.pw.toml"
hash = "996ec0faade5aa1d1207d87112fdc12ee6160a263c792b88181789f0fee01504"
metafile = true

[[files]]
file = "mods/no-void-structures-2.0.1.jar"
hash = "7f5aa433075e618795e41a70990f801c49bff2877821ba1b2b8c5e7916377ce5"

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89274e49cdb7fb45b73908113dad5b8355efcacd4408d40655b900fea6851a9b"
metafile = true

[[files]]
file = "mods/not-so-essential.toml"
hash = "f0db0758b3c30545d152b3e600e95a4cf78bf737e73e6e6fd0746b56480510ca"

[[files]]
file = "mods/numismatics.pw.toml"
hash = "6bc91a7c0feb2228bda4e7748f6cda92aaedd8cf915b33179a3443c92298ce1e"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "2f1fde18b44b782b0a33d21debda83a8657cb80423cd07158820c59a6430b6cc"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "bf75e4c6f87d1d4bcb43474e3a4bf4dde6b8044b8b16ec8d856b589bdef68b8f"
metafile = true

[[files]]
file = "mods/peripheralworks-forge-1.20.1-1.7.15.jar"
hash = "6c0a85203d3dfa847bdf08e5b75ec86f89821df648c308052c627aa856f8037b"

[[files]]
file = "mods/petrolpark.pw.toml"
hash = "e421c03353b137bb422067ff32aa1e460a0bbce8fa9c28eb86afa6559bfd79b5"
metafile = true

[[files]]
file = "mods/petrols-parts.pw.toml"
hash = "c516ea3e999741e7a73927d75eca9ca8955600cfae309e1abdeeea97608607b5"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "1385e780cace56ebb73204f67cc1ea2f26f5f82127a27e1fcb97b34fe6e27911"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "2c3c0448ed22ce054cc33338bed223f73fbd9cb1b9f2613943b165980d61dbb4"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "3d4707f3d3db0814a8795f39f6113f9e6d445574d37b75bd299f7d6044121c16"
metafile = true

[[files]]
file = "mods/power-grid.pw.toml"
hash = "c15bdfb3e1e6ac7ff9440ae5062208ff45f1eb1d7498c709c43ad1f399020f37"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "c61b9de69b78020007a6dde5ddb598fd996e79a13d1ad1bbbbe2f2bb86668aaa"
metafile = true

[[files]]
file = "mods/quarkponders.pw.toml"
hash = "762babdd0ff90cc5328949007aaee79ba9e3786d3db49e54a479cdadae8a3160"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "4fcfa912e5663f1445fe3c4df7cd05a4dae2b3f828b5cea8865c71c1c305050b"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "40822d840f9b4c1974978304301993f57d31ba4b99c5ef3b29df7376b6f9d93e"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "c42f911547877dffed96250139df94396f1dfa11c91f010555ae427e6147bad0"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "c78c644b13a40d016ab96cf012301136acec4ede3a5033cfc47a238762b3ab71"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "f08635219b039026ff20bf941a5bab8452adc6c831a72e8144ffeed8cc6af588"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "84a89780a891feb52c95b0237e18be787eb2b5ffa9a7583f525bb1806830689a"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "26951ba51d8d0909ea02053a7d2cdc80561b5ae92af07e0c1662b8aba25518c3"
metafile = true

[[files]]
file = "mods/telluriumforge-1.4.0-1.20.1-forge.jar"
hash = "12c0b0a481df4a05f0cb86c99d8b689d1a80b23b3da605c6f8b76fd343e1171c"

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "bd1999d0a8ed90edaf8b6a3b604e4cd7652ec57f9ee3bcff4b1eb28045d7e61b"
metafile = true

[[files]]
file = "mods/toms-peripherals.pw.toml"
hash = "96d5df365dd4736e1d2de85cd4a5b93dedf86fff7f33456268d8c4dcd172eb0e"
metafile = true

[[files]]
file = "mods/trackwork.pw.toml"
hash = "eec174cdff82a1464eb344cb4315b1164df5d6f32556465146d5072b262f0860"
metafile = true

[[files]]
file = "mods/turtlechargingstation-1.7.1-1.20.1-forge.jar"
hash = "c3d5c44f305b1f31e00e893d3a1046eb396f7904391fcfe70a7a50ac76536e60"

[[files]]
file = "mods/turtlematic.pw.toml"
hash = "8ba5a87af701d96b2223c717d4a7c09c3d77eedcceb8d2d18c6015c25281c5a6"
metafile = true

[[files]]
file = "mods/valkyrien-logistics.pw.toml"
hash = "c15eef121e77fcd4e8f6463d0459055f849dddb099cb52ede0a500d851802b20"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "f110b2595108d3266a76f9d21ad9f51fcdf871366f2582cbc3e91aeb2a8f35c8"
metafile = true

[[files]]
file = "mods/vmod-curseforge-port.pw.toml"
hash = "f035bdfb69b3cc0b731a3415cb4355bad26fb7c4676d34429be5106d5489ba8c"
metafile = true

[[files]]
file = "mods/voicechat-forge-1.20.1-2.6.12.jar"
hash = "02721705e295af1b54a5cbb8cbc7a44681906d6efb0a200be68bf972e5c9bb3c"

[[files]]
file = "mods/vs-hose-connectors.pw.toml"
hash = "d55a8e5184f60aca532d4a0090f66abd177815fd886d0537a031bdaca71f2c79"
metafile = true

[[files]]
file = "mods/vs_logistics-1.1.0.jar"
hash = "05c6af1b859a59abd8cfdb69c88ecb9a0ae8e644ea3bade036b910f793704fda"

[[files]]
file = "mods/vstuff.pw.toml"
hash = "cc91e215b10460507c65a523d517fa14ce855d129cb37da3b148a4b367a53ba9"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "19906fed2d8072a757cd46f80f414f22c3413215359f3dc5e877667b44f2a435"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "fe4a59eb731fcfae23e2e3fc1f9bbc725227409aa9c3e5b7a507a91a1c0d4d6f"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "19e361fc7080408992716bd9dac187602481610eeb040d9aa34ef8fc82c4f768"
metafile = true
