name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f354e0fe0170db63752d11266160879e34c0fb84e0a6318762372c591a9fc647"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
