name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a94a472026e3758db83e3c3101b206c7daa957c6c2516be36b816a9567ec8eb3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
